# Task 1:

1. Write a function to compute 5/0 and use try/except to catch the exceptions.

In [9]:
def division(x,y):
    try:
        result=x/y
    except ZeroDivisionError:
        print("Can't divide a Integer by Zero!")
        return None
    return result

division(5,0)

Can't divide a Integer by Zero!


2. Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

    Hint: Subject,Verb and Object should be declared in the program as shown below.
    
    subjects=["Americans ","Indians"]
    verbs=["play","watch"]
    objects=["Baseball","Cricket"]
    
    Output should come as below:
        Americans play Baseball.
        Americans play Cricket.
        Americans watch Baseball.
        Americans watch Cricket.
        Indians play Baseball.
        Indians play Cricket.
        Indians watch Baseball.
        Indians watch Cricket.

In [15]:
subjects=["Americans","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"]

for x in subjects:
    for y in verbs:
        for z in objects:
            print(f'{x} {y} {z}.')

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


# Task 2:

1. Write a function so that the columns of the output matrix are powers of the input vector.
    
    The order of the powers is determined by the increasing boolean argument. 
    Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power
    of N - i - 1.
    
    HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.


In [19]:
import numpy as np

In [43]:
def Vandermonde(ip_vector,power_order):
    #result=np.vander(ip_vector,increasing=power_order)
    N=len(ip_vector)
    if power_order==False:
        result=np.column_stack([ip_vector**(N-i-1) for i in range(0,N)])
    else:
        result=np.column_stack([ip_vector**i for i in range(0,N)])
    
    return result

In [46]:
vector = np.array([1, 2, 3, 5])
power_order = False
print(Vandermonde(vector,power_order))

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
